FROM oven/bun:1 as build

COPY . /build
WORKDIR /build
RUN bun install --frozen-lockfile
RUN bun run build

FROM nginx

COPY containers/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /build/dist /usr/share/nginx/html