version: '3.7'

services:
  sync:
    image: ${BACKEND_IMAGE}
    volumes:
      - database:/data
    env_file: .env
  frontend:
    image: ${FRONTEND_IMAGE}
    ports:
      - "8080:80"

volumes:
  database:
